apiVersion: v1
kind: Secret
metadata:
  name: ecomm-app-secrets
type: Opaque
data:
  db-username: dGVzdF91c2Vy
  db-password: dGVzdF9wYXNzd29yZA==
  db-name: ZWNvbWRi
  db-host: bWFyaWFkYi1zZXJ2aWNlCg==